#ifndef CONSTANTES_INCLUDED
#define CONSTANTES_INCLUDED

#define CANTIDAD_DE_ECUACIONES 10
#define CANTIDAD_DE_ARCHIVOS 10
#define LONG_DE_ECUACIONES 50
#define LONG_DE_SESIONES 51
#define LONG_NOMBRE_DE_ARCHIVO 51
#define RUTA_COMPLETA_ARCHIVO 66


#endif // CONSTANTES_INCLUDED
